import { useRef, useLayoutEffect, type CSSProperties } from 'react'
import { TemplateField, EditableTemplateBox as Box } from './TemplateFields'
import { TemplateEditingContext, calendarDays, templateDate } from './templateEditingModel'
import './TemplateEditing.css'
import { getBuiltInTemplate } from './templateCatalog'
import './TemplateBackground.css'
import './TemplateReferences.css'
import './TemplateReferences2.css'
import './WeeklyOpenJournal.css'
import { WeeklyOpenJournal } from './WeeklyOpenJournal'

const days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']
const Lines = ({ count = 4 }: { count?: number }) => <div className="tpl-lines">{Array.from({ length: count }, (_, index) => <i key={index} />)}</div>

function getLocalDateKey(date: Date) {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}


export function TemplateBackground({ templateId, spreadSide, data = {}, onChange, onDuplicateSection, weekStart, onWeeklyWeekChange }: {
  templateId: string; spreadSide?: 'left' | 'right'; data?: Record<string, unknown>
  onChange?: (data: Record<string, unknown>) => void
  onDuplicateSection?: (title: string, text: string) => void
  weekStart?: string
  onWeeklyWeekChange?: (weekStart: string) => Promise<void>
}) {
  const latest = useRef(data)
  useLayoutEffect(() => { latest.current = data }, [data])
  const update = (key: string, value: unknown) => {
    const next = { ...latest.current, [key]: value }
    latest.current = next
    onChange?.(next)
  }
  const template = getBuiltInTemplate(templateId)
  if (!template) return null
  const layout = template.layout
  const now = templateDate(data)
  const currentMonthIndex = now.getMonth()
  const currentMonth = now.toLocaleDateString('pt-BR', { month: 'long' }).toLocaleUpperCase('pt-BR')
  const currentYear = now.getFullYear()
  const startOfWeek = new Date(now)
  startOfWeek.setDate(now.getDate() - ((now.getDay() + 6) % 7))
  const defaultWeekStart = getLocalDateKey(startOfWeek)
  const weekDates = days.map((_, index) => {
    const date = new Date(startOfWeek)
    date.setDate(startOfWeek.getDate() + index)
    return date.getDate()
  })
  return <TemplateEditingContext.Provider value={onChange ? { data, update, duplicate: onDuplicateSection } : null}><div className={`planner-template-base template-${layout}`} style={{ '--template-accent': template.accent } as CSSProperties} aria-hidden={onChange ? undefined : true}>
    {layout !== 'weekly-open-journal' && <div className="tpl-date-controls">{layout.includes('weekly') || template.category === 'Weekly' || layout === 'weekly-scrapbook'
      ? <TemplateField field="templateDate" type="date" value={String(data.templateDate ?? new Date().toLocaleDateString('en-CA'))} label="Semana escolhida" />
      : template.category === 'Daily' || template.category === 'Study' ? <TemplateField field="templateDate" type="date" value={String(data.templateDate ?? new Date().toLocaleDateString('en-CA'))} label="Data da página" /> : <><TemplateField field="month" value={currentMonth} label="M?s" /><TemplateField field="year" value={String(currentYear)} label="Ano" /></>}</div>
    }
    <header className="tpl-heading"><span>MATCHA PLANNER · {template.category.toUpperCase()}</span><h2><TemplateField field="title" value={template.name} label="T?tulo do template" /></h2><i /></header>

    {layout === 'dashboard-blue' && <div className="tpl-dashboard-grid"><Box title="MAIN TASK STRATEGY" className="tpl-main"><div className="tpl-strategy"><span>01 · START</span><span>02 · FOCUS</span><span>03 · REVIEW</span><span>04 · DONE</span></div></Box><Box title="TODAY"><Lines count={5} /></Box><Box title="THIS WEEK"><Lines count={5} /></Box><Box title="PROGRESS"><div className="tpl-progress">—</div></Box><Box title="NOTES"><Lines count={7} /></Box></div>}
    {layout === 'dashboard-kawaii' && <div className="tpl-kawaii-grid"><Box title="HELLO, LOVELY DAY" className="tpl-window"><div className="tpl-window-dots">● ● ●</div><Lines count={2} /></Box><Box title="TO DO"><Lines count={5} /></Box><Box title="WEATHER"><div className="tpl-cloud">○</div></Box><Box title="MEMORY"><div className="tpl-photo-placeholder">＋</div></Box><Box title="A LITTLE NOTE"><Lines count={5} /></Box></div>}
    {layout === 'roadmap' && <div className={`tpl-ref-roadmap ${spreadSide ? `is-spread-${spreadSide}` : ''}`}>
      {spreadSide !== 'right' && <section className="tpl-road-left"><h3><TemplateField field="heading:today-s-focus" value="TODAY'S FOCUS" label="TODAY'S FOCUS" /></h3><div className="tpl-focus-row"><Lines count={5} /><div className="tpl-mini-timetable">{Array.from({ length: 12 }, (_, i) => <span key={i}>{i + 7}:00</span>)}</div></div><h4><TemplateField field="heading:free-space-to-grow" value="FREE SPACE TO GROW" label="FREE SPACE TO GROW" /></h4><div className="tpl-care-grid">{['Health', 'Care', 'Work', 'Learn'].map(item => <span key={item}>{item}</span>)}</div><Box title="SELF-MAINTENANCE"><Lines count={5} /></Box><footer><span>BEST THING THAT HAPPENED</span><span>TODAY I LEARNED</span><span>TODAY IN ONE WORD</span></footer></section>}
      {spreadSide !== 'left' && <section className="tpl-road-right"><h3><TemplateField field="heading:space-of-infinite-possibility-" value="SPACE OF INFINITE POSSIBILITY:" label="SPACE OF INFINITE POSSIBILITY:" /></h3><div className="tpl-road-stickers"><article className="yellow"><b>LOVE WHAT YOU DO</b><i>LOVE</i></article><article className="blue"><b>TODAY, I WILL SPEND 30 MINS ON...</b></article><article className="cream"><b>I WILL REWARD MYSELF WITH:</b></article><article className="navy"><b>I AM ON THE RIGHT PATH.</b></article></div><div className="tpl-audio-strip">PREV &nbsp; PAUSE &nbsp; NEXT</div><Box title="WHERE I'M AT"><Lines count={7} /></Box></section>}
      <div className="tpl-edge-tabs">{(spreadSide === 'left' ? ['ROADMAP','YEAR','MONTHLY','REFLECTION'] : spreadSide === 'right' ? ['BLANK','DOT','GRID','STICKERS'] : ['ROADMAP','YEAR','MONTHLY','REFLECTION','BLANK','DOT','GRID','STICKERS']).map(tab => <span key={tab}>{tab}</span>)}</div>
    </div>}
    {layout === 'project-month' && <div className="tpl-ref-project"><div className="tpl-project-tabs"><span>PROJECT</span><span>TRACKER</span><span>EXPENSE</span><span>REFLECT</span><span>JOURNAL</span></div><h3><TemplateField field="title" value="Project Planner" label="T?tulo do projeto" /></h3><div className="tpl-project-body"><section className="tpl-project-ideas"><Box title="PROJECT IDEA"><Lines count={4} /></Box><Box title="NOTES"><Lines count={4} /></Box></section><Box title="ACTION PLAN" className="tpl-action-plan"><Lines count={9} /></Box><section className="tpl-process"><header><b>Process Tracker</b><span>Personal / Travel / Workout / Work / Content</span></header><div className="tpl-project-calendar">{days.map(day => <b key={day}>{day.slice(0,1)}</b>)}{calendarDays(currentYear, currentMonthIndex).map((day, i) => <span data-calendar-day={day ?? ''} key={i}>{day}</span>)}</div></section></div><footer className="tpl-project-journal"><strong><TemplateField field="month" value={currentMonth} label="M?s do projeto" /></strong><Lines count={3} /><div><TemplateField field="heading:month-goals" value="MONTH GOALS" label="Título MONTH GOALS" /><TemplateField field="month-goals" multiline placeholder="Defina sua meta..." label="MONTH GOALS" /></div></footer></div>}
    {layout === 'study-grid' && <div className="tpl-ref-study"><header><b><TemplateField field="study-date-label" type="date" value={getLocalDateKey(now)} label="Data do estudo" /></b><div>{days.map(day => <span key={day}>{day.slice(0,1)}</span>)}</div></header><section className="tpl-study-memo"><Box title="MEMO"><Lines count={3} /></Box><div className="tpl-dday"><small><TemplateField field="dday-label" value="D-DAY" label="Título D-DAY" /></small><strong>—</strong><b><TemplateField field="dday-duration" value="__H__M" label="Duração D-DAY" /></b></div></section><div className="tpl-study-columns"><section><h3><TemplateField field="heading:task" value="TASK" label="TASK" /></h3><div className="tpl-korean-table">{['01','02','03','04'].flatMap((subject, group) => Array.from({ length: 3 }, (_, i) => <div key={`${subject}${i}`}><b>{i === 0 ? subject : ''}</b><span /><i className={`ink-${group}`} /></div>))}</div></section><section><h3><TemplateField field="heading:timetable" value="TIMETABLE" label="TIMETABLE" /></h3><div className="tpl-study-hours">{Array.from({ length: 17 }, (_, i) => <div key={i}><b>{i + 7}</b>{Array.from({ length: 5 }, (_, j) => <span key={j} />)}</div>)}</div></section></div></div>}
    {layout === 'weekly-clean' && <div className="tpl-ref-week-clean"><header><h3><TemplateField field="title" value="WEEK PLANNER" label="T?tulo da semana" /></h3><span>{currentYear} GOALS &nbsp; / &nbsp; RESULTS</span></header><div className="tpl-clean-columns"><section className="tpl-clean-planning"><h4><TemplateField field="heading:planning" value="PLANNING" label="PLANNING" /></h4>{days.map((day,i) => <article key={day}><b>{weekDates[i]}<small>{day}</small></b><Lines count={2}/><div className="tpl-week-day-content"><TemplateField field={`day:${i}`} multiline placeholder="" label={`Plano ${day}`} /></div>{i===2 && <i>PHOTO</i>}</article>)}</section><aside><Box title="PRIORITIES"><Lines count={4}/></Box><Box title="TO DO LIST"><Lines count={9}/></Box><Box title="HABITS"><div className="tpl-habit-matrix">{['HABIT 1','HABIT 2','HABIT 3','HABIT 4'].map(name => <div key={name}><b>{name}</b>{Array.from({length:7},(_,i)=><i key={i}/>)}</div>)}</div></Box></aside></div><footer><b><TemplateField field="heading:notes" value="NOTES" label="T?tulo NOTES" /></b><TemplateField field="notes" multiline placeholder="Adicione uma nota..." label="NOTES" /><div className="tpl-clean-collage"><span>PHOTO</span><span>COLLAGE<br/>SPACE</span><span>{currentMonth}</span></div></footer></div>}
    {layout === 'weekly-dots' && <div className="tpl-ref-dots"><header><h3><TemplateField field="heading:week-range" value={`THIS WEEK ${weekDates[0]}/${now.getMonth()+1} - ${weekDates[6]}/${now.getMonth()+1}`} label="Semana" /></h3><div className="tpl-week-mini"><TemplateField field="week-days-label" value="Mo Tu We Th Fr Sa Su" label="Dias da semana" /></div><Box title="Motivation of the week"><Lines count={2}/></Box></header><div className="tpl-dot-days">{days.slice(0,6).map(day => <Box title={day[0]+day.slice(1).toLowerCase()} key={day} />)}<div className="tpl-dot-cat"><i/><i/><b>o . o</b><span>Mo<br/>Tu<br/>We<br/>Th<br/>Fr<br/>Sa<br/>Su</span></div><Box title="Sunday" /></div></div>}
    {layout === 'weekly-cute' && <div className="tpl-ref-cute"><header><h3><TemplateField field="heading:weekly-plan" value="Weekly plan" label="Weekly plan" /></h3><strong>LOVE</strong><i>PASTEL</i></header><div className="tpl-cute-columns"><section>{days.map((day,i)=><article key={day}><b>{day.slice(0,3)[0]+day.slice(1,3).toLowerCase()}</b><Lines count={i===6?2:3}/><i>{['NOTE','STAR','WARN','HOME','DONE','BREAK','MOOD'][i]}</i></article>)}</section><aside><Box title="GOALS"><Lines count={5}/></Box><Box title="PRIORITIES"><Lines count={5}/></Box><Box title="NOTES"><Lines count={5}/></Box></aside></div><footer><b>Habit tracker</b><div>{['HABIT 1','HABIT 2','HABIT 3','HABIT 4'].map(name=><p key={name}><span>{name}</span>{Array.from({length:7},(_,i)=><i key={i}/>)}</p>)}</div></footer></div>}
    {layout === 'daily-focus' && <div className="tpl-ref-daily"><header><h3><small><TemplateField field="heading:daily-label" value="daily" label="Título daily" /></small> <TemplateField field="heading:study-label" value="STUDY" label="Título STUDY" /></h3><span><TemplateField field="daily-focus-date" type="date" value={getLocalDateKey(now)} label="Data do estudo" /></span></header><div className="tpl-daily-top"><Box title="OBJECTIVES"><Lines count={3}/></Box><Box title="WEATHER / MOOD"><div className="tpl-weather-icons">{['SUN','CLOUD','RAIN','HAPPY','CALM'].map(item => <span key={item}>{item}</span>)}</div></Box></div><div className="tpl-daily-columns"><section><Box title="PRIORITY"><Lines count={5}/></Box><div className="tpl-todo-code"><h4><TemplateField field="heading:to-do-list-color-code" value="TO DO LIST / COLOR CODE" label="TO DO LIST / COLOR CODE" /></h4>{Array.from({length:18},(_,i)=><p key={i}><i/><span/><b/></p>)}</div></section><section><h4><TemplateField field="heading:time" value="TIME" label="TIME" /></h4><div className="tpl-hour-grid"><header><span>10</span><span>20</span><span>30</span><span>40</span><span>50</span><span>60</span></header>{Array.from({length:24},(_,i)=><p key={i}><b>{String(i+1).padStart(2,'0')}:00</b>{Array.from({length:6},(_,j)=><i key={j}/>)}</p>)}</div><Box title="NOTES"><Lines count={5}/></Box></section></div></div>}
    {layout === 'monthly-focus' && <div className="tpl-ref-monthly"><nav>{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].map((month,index)=><span className={index===currentMonthIndex?'active':''} key={month}>{month}</span>)}</nav><div className="tpl-month-main"><aside><h3><TemplateField field="heading:calendar" value="CALENDAR" label="CALENDAR" /></h3><div className="tpl-small-calendar">{['S','M','T','W','T','F','S'].map((d,i)=><b key={i}>{d}</b>)}{calendarDays(currentYear, currentMonthIndex, false).map((day, i) => <span data-calendar-day={day ?? ''} key={i}>{day}</span>)}</div><Box title="SCHEDULE"><Lines count={9}/></Box></aside><section><Box title="FOCUS"><Lines count={3}/></Box><Box title="GOAL"><div className="tpl-goal-bars">{Array.from({length:6},(_,i)=><p key={i}><span/><i><b style={{width:'0%'}}/></i></p>)}</div></Box><Box title="TO DO"><Lines count={9}/></Box></section><section className="tpl-duration"><h3><TemplateField field="heading:duration" value="DURATION" label="DURATION" /></h3>{Array.from({length:31},(_,i)=><p key={i}><b>{i+1}</b></p>)}</section></div><Box title="TRACKER" className="tpl-month-tracker"><div>{Array.from({length:5},(_,r)=><p key={r}><b>HABIT {r+1}</b>{Array.from({length:31},(_,i)=><i key={i}/>)}</p>)}</div></Box></div>}
    {layout === 'weekly-scrapbook' && <div className="tpl-ref-scrap"><div className="tpl-scrap-tabs">PROJECT / TRACKER / EXPENSE / REFLECT / JOURNAL</div><div className="tpl-scrap-days">{days.map((day,i)=><article className={`scrap-day scrap-${i+1}`} key={day}><h3>{String(weekDates[i]).padStart(2,'0')} <small>{day[0]+day.slice(1).toLowerCase()}</small></h3><b>NOTE</b><Lines count={3}/><i>{['NOTE','STAR','WARN','HOME','DONE','BREAK','MOOD'][i]}</i></article>)}</div><footer><div className="tpl-scrap-calendar">{currentMonth} {currentYear}<br/>M T W T F S S</div><div className="tpl-scrap-note"><b>WEEK NOTES</b><Lines count={3}/></div></footer></div>}
    {layout === 'daily-time-block' && <div className="tpl-ref-timeblock"><header><span><TemplateField field="timeblock-date" type="date" value={getLocalDateKey(now)} label="Data do time-block" /></span><h3><TemplateField field="heading:daily-time-block-study" value="Daily Time-Block Study" label="Daily Time-Block Study" /></h3><b><TemplateField field="timeblock-mood" value="MOOD ○ ○ ○ ○ ○" label="Humor do dia" /></b></header><div className="tpl-timeblock-meta"><Box title="GOAL"><Lines count={3} /></Box><Box title="PRIORITY"><Lines count={3} /></Box></div><div className="tpl-timeblock-body"><section><Box title="TASKS / COLOR CODE"><div className="tpl-check-lines">{Array.from({ length: 12 }, (_, i) => <p key={i}><i /><span /></p>)}</div></Box><Box title="NOTES"><Lines count={7} /></Box></section><section><h4><TemplateField field="heading:timetable" value="TIMETABLE" label="TIMETABLE" /></h4><div className="tpl-timeblock-hours">{Array.from({ length: 16 }, (_, i) => <p key={i}><b>{String(i + 7).padStart(2, '0')}:00</b><i /><i /><i /><i /></p>)}</div><footer><span><TemplateField field="timeblock-total" value="TOTAL ____ h" label="Total de horas" /></span><span><TemplateField field="timeblock-progress" value="PROGRESS ____ %" label="Progresso" /></span></footer></section></div></div>}
    {layout === 'weekly-open-journal' && <WeeklyOpenJournal
      spreadSide={spreadSide}
      weekStart={weekStart ?? defaultWeekStart}
      onWeekChange={onWeeklyWeekChange ?? (async () => undefined)}
      enabled={Boolean(onChange && weekStart && onWeeklyWeekChange)}
    />}
  </div></TemplateEditingContext.Provider>
}
