"""add page paper type

Revision ID: 02d7b1d45c78
Revises: 87028be90d9e
Create Date: 2026-09-03 13:10:19.351164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d7b1d45c78'
down_revision: Union[str, Sequence[str], None] = '87028be90d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('paper_type', sa.String(length=20), server_default='blank', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'paper_type')
    # ### end Alembic commands ###
