"""align auth session uniqueness

Revision ID: 1bb9ef4589aa
Revises: f3c2a1b4d5e6
Create Date: 2026-09-12 21:39:04.485395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb9ef4589aa'
down_revision: Union[str, Sequence[str], None] = 'f3c2a1b4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_auth_sessions_session_key'), 'auth_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_auth_sessions_session_key'), 'auth_sessions', ['session_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
