"""add media library

Revision ID: 370e747e407c
Revises: bba93ec2bd5d
Create Date: 2026-09-08 17:18:19.162743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370e747e407c'
down_revision: Union[str, Sequence[str], None] = 'bba93ec2bd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=30), server_default='sticker', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('kit_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_media_library_items_kit_name'), 'media_library_items', ['kit_name'], unique=False)
    op.create_index(op.f('ix_media_library_items_user_id'), 'media_library_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_library_items_user_id'), table_name='media_library_items')
    op.drop_index(op.f('ix_media_library_items_kit_name'), table_name='media_library_items')
    op.drop_table('media_library_items')
    # ### end Alembic commands ###
