"""add media geometry

Revision ID: 5e9a8d7b819e
Revises: 5813d644e2de
Create Date: 2026-09-04 16:37:37.449695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9a8d7b819e'
down_revision: Union[str, Sequence[str], None] = '5813d644e2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_media', sa.Column('x', sa.Integer(), server_default='40', nullable=False))
    op.add_column('page_media', sa.Column('y', sa.Integer(), server_default='40', nullable=False))
    op.add_column('page_media', sa.Column('width', sa.Integer(), server_default='240', nullable=False))
    op.add_column('page_media', sa.Column('height', sa.Integer(), server_default='180', nullable=False))
    op.add_column('page_media', sa.Column('rotation', sa.Integer(), server_default='0', nullable=False))
    op.add_column('page_media', sa.Column('z_index', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_media', 'z_index')
    op.drop_column('page_media', 'rotation')
    op.drop_column('page_media', 'height')
    op.drop_column('page_media', 'width')
    op.drop_column('page_media', 'y')
    op.drop_column('page_media', 'x')
    # ### end Alembic commands ###
