"""add habits and habit completions

Revision ID: 717bc4ba7ad7
Revises: c8a4e2d91f70
Create Date: 2026-09-21 18:19:30.525519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717bc4ba7ad7'
down_revision: Union[str, Sequence[str], None] = 'c8a4e2d91f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('color', sa.String(length=20), server_default='#9CA362', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_habits_user_active', 'habits', ['user_id', 'active'], unique=False)
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'completion_date', name='uq_habit_completions_habit_date')
    )
    op.create_index('ix_habit_completions_habit_date', 'habit_completions', ['habit_id', 'completion_date'], unique=False)
    op.create_index(op.f('ix_habit_completions_habit_id'), 'habit_completions', ['habit_id'], unique=False)
    op.add_column('reminders', sa.Column('habit_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reminders_habit_id'), 'reminders', ['habit_id'], unique=False)
    op.create_foreign_key(
    'fk_reminders_habit_id_habits',
    'reminders',
    'habits',
    ['habit_id'],
    ['id'],
    ondelete='CASCADE',
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    'fk_reminders_habit_id_habits',
    'reminders',
    type_='foreignkey',
)
    op.drop_index(op.f('ix_reminders_habit_id'), table_name='reminders')
    op.drop_column('reminders', 'habit_id')
    op.drop_index(op.f('ix_habit_completions_habit_id'), table_name='habit_completions')
    op.drop_index('ix_habit_completions_habit_date', table_name='habit_completions')
    op.drop_table('habit_completions')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_index('ix_habits_user_active', table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
