"""add media locked

Revision ID: bba93ec2bd5d
Revises: 5e9a8d7b819e
Create Date: 2026-09-08 16:17:16.415908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba93ec2bd5d'
down_revision: Union[str, Sequence[str], None] = '5e9a8d7b819e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_media', sa.Column('locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_media', 'locked')
    # ### end Alembic commands ###
