import assert from 'node:assert/strict'

// Uses the same isolated real PostgreSQL/API session as academic-browser.mjs.
export async function verifyIntegrity({ api, navigate, evaluate, fill, clickText, until, cdp, today, subject, otherSubject, project }) {
  console.log('Integrity: Tasks / Today');
  await navigate('/tasks')
  await until(() => evaluate('!!document.querySelector(".tasks-form-grid input[type=text]")'), 'Task form missing')
  await fill('.tasks-form-grid input[type=text]', 'Integridade cruzada UI')
  await fill('.tasks-form-grid input[type=date]', today)
  await until(() => evaluate(`!!document.querySelector('.tasks-form-grid select option[value="${subject.id}"]')`), 'Task subjects not loaded')
  await fill('.tasks-form-grid select', String(subject.id))
  await evaluate(`(() => { const select=[...document.querySelectorAll('.tasks-form-grid label')].find(l=>l.textContent.trim().startsWith('Projeto')).querySelector('select'); Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(select, '${project.id}'); select.dispatchEvent(new Event('change',{bubbles:true})); })()`)
  await evaluate('document.querySelector(".tasks-page form button[type=submit]").click()')
  const task = await until(async () => (await api('/tasks')).find(t => t.text === 'Integridade cruzada UI'), 'Task not created through form')
  assert.equal(task.subject_id, subject.id); assert.equal(task.project_id, project.id)
  assert.equal(task.completed_at, null)
  await navigate('/today')
  await until(() => evaluate('document.querySelector(".today-receipt-lines")?.textContent.includes("Integridade cruzada UI")'), 'Today missing same task')
  await evaluate(`[...document.querySelectorAll('.today-receipt-lines label')].find(l=>l.textContent.includes('Integridade cruzada UI')).querySelector('input').click()`)
  await until(async () => (await api('/tasks')).find(t => t.id === task.id).done, 'Today did not update original task')
  assert((await api('/tasks')).find(t => t.id === task.id).completed_at)
  await navigate('/tasks')
  await until(() => evaluate(`document.querySelector('#task-${task.id}')?.classList.contains('done')`), 'Tasks did not reflect Today')
  await cdp('Page.reload')
  await until(() => evaluate(`document.querySelector('#task-${task.id}')?.classList.contains('done')`), 'Task completion lost after F5')
  await navigate('/weekly-review')
  await until(() => evaluate('document.querySelector(".weekly-grid")?.textContent.includes("Integridade cruzada UI")'), 'Planning missing completion')
  const agenda = await api('/agendas', 'POST', { title: 'Auditoria Receipt' })
  const page = await api(`/agendas/${agenda.id}/pages`, 'POST', { title: 'Recibo real' })
  const receipt = await api('/canvas/elements', 'POST', { surface_type: 'page', page_id: page.id, element_type: 'widget:task-receipt', data: { taskIds: [task.id] }, width: 300, height: 420 })
  await cdp('Page.navigate', { url: await evaluate('location.origin') + `/agenda/${agenda.id}?page=${page.id}` })
  try {
    await until(() => evaluate('document.querySelector(".task-receipt-item input")?.checked'), 'Receipt missing completed global task')
  } catch (error) {
    console.log(await evaluate('document.body.innerText'))
    throw error
  }
  await cdp('Page.reload')
  await until(() => evaluate('document.querySelector(".task-receipt-item input")?.checked'), 'Receipt completion lost after F5')
  await evaluate('document.querySelector(".task-receipt-item input").click()')
  await until(async () => !(await api('/tasks')).find(t => t.id === task.id).done, 'Receipt reopen failed')
  assert.equal((await api('/tasks')).find(t => t.id === task.id).completed_at, null)
  await cdp('Page.reload')
  await until(() => evaluate('!!document.querySelector(".task-receipt-item input") && !document.querySelector(".task-receipt-item input").checked'), 'Receipt reopened state lost after F5')
  assert.deepEqual((await api(`/canvas/elements?surface_type=page&page_id=${page.id}`)).find(e => e.id === receipt.id).data, { taskIds: [task.id] })
  await navigate('/weekly-review')
  await until(() => evaluate('!!document.querySelector(".weekly-grid")'), 'Planning missing')
  assert(!await evaluate('document.querySelector(".weekly-card ul")?.textContent.includes("Integridade cruzada UI")'))
  await navigate('/today')
  await until(() => evaluate(`!![...document.querySelectorAll('.today-receipt-lines label')].find(l=>l.textContent.includes('Integridade cruzada UI'))`), 'Today reload missing task')
  assert.equal(await evaluate(`[...document.querySelectorAll('.today-receipt-lines label')].find(l=>l.textContent.includes('Integridade cruzada UI')).querySelector('input').checked`), false)
  await navigate('/deadlines')
  await until(() => evaluate('!!document.querySelector(\'[aria-label="Concluir Integridade cruzada UI"]\')'), 'Deadlines missing same task')
  await evaluate('document.querySelector(\'[aria-label="Concluir Integridade cruzada UI"]\').click()')
  await until(async () => (await api('/tasks')).find(t => t.id === task.id).done, 'Deadline completion not persisted')
  await navigate('/tasks')
  await until(() => evaluate(`document.querySelector('#task-${task.id}')?.classList.contains('done')`), 'Tasks did not reflect deadline completion')

  console.log('Integrity: Calendar / Today');
  const event = await api('/events', 'POST', { title: 'Evento para editar UI', subject_id: subject.id, project_id: project.id, starts_at: `${today}T00:01:00-03:00`, ends_at: `${today}T00:10:00-03:00`, reminder_minutes: 15 })
  await navigate(`/calendar?date=${today}`)
  await until(() => evaluate('document.querySelector(".selected-events")?.textContent.includes("Evento para editar UI")'), 'Calendar event missing')
  await evaluate(`[...document.querySelectorAll('.event-card')].find(e=>e.textContent.includes('Evento para editar UI')).querySelector('button').click()`)
  await fill('.event-form input[type=text]', 'Evento atualizado UI')
  await until(() => evaluate(`!!document.querySelector('.event-form select option[value="${otherSubject.id}"]')`), 'Event subjects not loaded')
  await fill('.event-form select', String(otherSubject.id))
  await clickText('.event-form button', 'Salvar alterações')
  await until(async () => (await api(`/events/${event.id}`)).title === 'Evento atualizado UI', 'Calendar edit did not persist')
  const updatedEvent = await api(`/events/${event.id}`)
  assert.equal(updatedEvent.subject_id, otherSubject.id)
  assert.equal(updatedEvent.project_id, project.id)
  assert.equal(updatedEvent.reminder_minutes, 15)
  assert.equal(new Date(updatedEvent.ends_at).getTime() - new Date(updatedEvent.starts_at).getTime(), 9 * 60_000)
  await navigate('/today')
  await until(() => evaluate('document.body.textContent.includes("Evento atualizado UI")'), 'Today did not reflect edited event')
  await cdp('Page.reload')
  await until(() => evaluate('document.body.textContent.includes("Evento atualizado UI")'), 'Event update lost after F5')
  for (const path of ['/weekly-review', '/deadlines', `/organization?section=academic&subject=${otherSubject.id}`]) {
    await navigate(path)
    await until(() => evaluate('document.body.textContent.includes("Evento atualizado UI")'), 'Event update missing at ' + path)
    await cdp('Page.reload')
    await until(() => evaluate('document.body.textContent.includes("Evento atualizado UI")'), 'Event update lost after F5 at ' + path)
  }

  console.log('Integrity: Studies / Today / Academic');
  await navigate('/studies')
  await until(() => evaluate('!!document.querySelector(".study-form-card select")'), 'Study form missing')
  await until(() => evaluate(`!!document.querySelector('.study-form-card select option[value="${subject.id}"]')`), 'Study subjects not loaded')
  await fill('.study-form-card select', String(subject.id))
  await fill('.study-form-card input[placeholder="Funções e parâmetros"]', 'Sessão cruzada UI')
  await fill('.study-form-card input[type=date]', today)
  await fill('.duration-fields label:first-child input', '0')
  await fill('.duration-fields label:last-child input', '35')
  await clickText('.study-form-card button', 'Registrar estudo')
  const study = await until(async () => (await api('/studies')).find(s => s.topic === 'Sessão cruzada UI'), 'Study not created from form')
  assert.equal(study.subject_id, subject.id); assert.equal(study.duration_minutes, 35)
  await navigate('/today')
  const totalMinutes = (await api('/studies')).filter(s => s.study_date === today).reduce((sum, s) => sum + s.duration_minutes, 0)
  await until(() => evaluate(`document.querySelector('.today-studies strong')?.textContent.trim() === '${totalMinutes} min'`), 'Today did not load study total')
  await navigate(`/organization?section=academic&subject=${subject.id}`)
  await until(() => evaluate('document.querySelector(".academic-detail")?.textContent.includes("Sessão cruzada UI")'), 'Academic detail did not load same study')
  await api(`/studies/${study.id}`, 'PATCH', { subject_id: otherSubject.id, project_id: project.id })
  await api(`/tasks/${task.id}`, 'PATCH', { subject_id: otherSubject.id })
  await api(`/projects/${project.id}`, 'PATCH', { subject_id: otherSubject.id })
  await navigate(`/organization?section=academic&subject=${otherSubject.id}`)
  await until(() => evaluate('document.querySelector(".academic-detail")?.textContent.includes("Sessão cruzada UI")'), 'Association change not reflected')
  assert(await evaluate('document.querySelector(".academic-sections").textContent.includes("Integridade cruzada UI")'))
  assert(await evaluate('document.querySelector(".academic-sections").textContent.includes("Evento atualizado UI")'))
  assert(await evaluate(`document.querySelector('.academic-sections').textContent.includes(${JSON.stringify(project.title)})`))
  await cdp('Page.reload')
  await until(() => evaluate('document.querySelector(".academic-detail")?.textContent.includes("Sessão cruzada UI")'), 'Association lost after F5')
  const results = await api('/search?q=Integridade%20cruzada')
  assert(results.some(result => result.type === 'task' && result.id === task.id))
  assert.equal((await api('/tasks')).filter(t => t.text === 'Integridade cruzada UI').length, 1)
  assert.equal((await api('/studies')).filter(s => s.topic === 'Sessão cruzada UI').length, 1)
  const exported = await api('/data/export')
  assert.equal(exported.tasks.find(t => t.id === task.id).subject_id, otherSubject.id)
  assert.equal(exported.study_sessions.find(s => s.id === study.id).subject, otherSubject.name)
  const renamedSubject = 'História renomeada auditoria'
  const renamedProject = 'Projeto renomeado auditoria'
  await api(`/subjects/${otherSubject.id}`, 'PATCH', { name: renamedSubject })
  await api(`/projects/${project.id}`, 'PATCH', { title: renamedProject })
  for (const path of ['/tasks', '/calendar', '/studies', '/organization?section=projects', '/weekly-review', '/deadlines']) {
    await navigate(path)
    await until(() => evaluate(`document.body.textContent.includes(${JSON.stringify(renamedSubject)})`), 'Subject rename missing at ' + path)
    if (['/tasks', '/organization?section=projects', '/weekly-review', '/deadlines'].includes(path)) {
      await until(() => evaluate(`document.body.textContent.includes(${JSON.stringify(renamedProject)})`), 'Project rename missing at ' + path)
    }
    await cdp('Page.reload')
    await until(() => evaluate(`document.body.textContent.includes(${JSON.stringify(renamedSubject)})`), 'Rename lost after F5 at ' + path)
  }
  const finalExport = await api('/data/export')
  assert.equal(finalExport.study_sessions.find(s => s.id === study.id).subject, renamedSubject)
  assert.equal(finalExport.projects.find(p => p.id === project.id).title, renamedProject)
  assert.equal(finalExport.projects.find(p => p.id === project.id).subject_id, otherSubject.id)
  assert((await api('/search?q=Hist%C3%B3ria%20renomeada')).some(r => r.type === 'study' && r.id === study.id))
  console.log('Integrity: Habits / Today / Planning / Data')
  const habit = await api('/habits', 'POST', { name: 'Hábito auditoria', days_of_week: [0, 1, 2, 3, 4, 5, 6] })
  await navigate('/today')
  await clickText('.today-mission-layout nav button', 'HABITS')
  await until(() => evaluate('document.querySelector(".today-habit-list")?.textContent.includes("Hábito auditoria")'), 'Habit missing in Today')
  await evaluate(`[...document.querySelectorAll('.today-habit-row')].find(e=>e.textContent.includes('Hábito auditoria')).click()`)
  await until(async () => (await api(`/habit-completions?start=${today}&end=${today}`)).some(c => c.habit_id === habit.id), 'Habit completion not persisted')
  await cdp('Page.reload')
  await clickText('.today-mission-layout nav button', 'HABITS')
  await until(() => evaluate(`[...document.querySelectorAll('.today-habit-row')].find(e=>e.textContent.includes('Hábito auditoria'))?.getAttribute('aria-pressed') === 'true'`), 'Habit completion lost after F5')
  const weekStart = new Date(`${today}T12:00:00`)
  weekStart.setDate(weekStart.getDate() - (weekStart.getDay() + 6) % 7)
  const start = `${weekStart.getFullYear()}-${String(weekStart.getMonth() + 1).padStart(2, '0')}-${String(weekStart.getDate()).padStart(2, '0')}`
  const completions = await api(`/habit-completions?start=${start}&end=${today}`)
  await navigate('/weekly-review')
  await until(() => evaluate(`Number([...document.querySelectorAll('.planning-stats > div')].find(e=>e.textContent.includes('Hábitos concluídos'))?.querySelector('strong').textContent) === ${completions.length}`), 'Planning habit count mismatch')
  const habitBackup = await api('/data/export')
  assert(habitBackup.habits.some(h => h.id === habit.id))
  assert(habitBackup.habit_completions.some(c => c.habit_id === habit.id))
  console.log('PASS: integrity cross-screen UI flows Tasks ↔ Today ↔ Deadlines, Calendar → Today, Studies → Today/Academic, association changes, export and search; real IDs, completion timestamps and F5 verified.')
}
